"use strict";
// Generated by the _Build.bat or .sh scripts. 
class _BuildRecord {
    static buildTime() { return new Date(2025, (parseInt("08") - 1), parseInt("03"), parseInt("11"), parseInt("16"), parseInt("06")); }
    static version() { return "unknown"; }
}
