"use strict";
// Generated by the _Build.bat or .sh scripts. 
class _BuildRecord {
    static buildTime() { return new Date(2025, (parseInt("07") - 1), parseInt("19"), parseInt("11"), parseInt("32"), parseInt("48")); }
    static version() { return "unknown"; }
}
