"use strict";
// Generated by the _Build.bat or .sh scripts. 
class _BuildRecord {
    static buildTime() { return new Date(2025, (parseInt("09") - 1), parseInt("01"), parseInt("22"), parseInt("32"), parseInt("38")); }
    static version() { return "unknown"; }
}
